variables:
  GIT_SUBMODULE_STRATEGY: none
  FRONTEND_BUILD_URI: "https://git.inp.nsk.su/api/v4/projects/cmd3%2Fcaendc%2Ffrontend/jobs/3556/artifacts/build.tar.gz"

stages:
  - build
  - release
  - deploy

build_wheel:
  stage: build
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/python:3.11-alpine
  before_script:
    - apk add curl
  script:
    - ls -lh
    - |
      cd caen_tools/WebService/frontend
      curl --location --output build.tar.gz --header "JOB-TOKEN: $CI_JOB_TOKEN" "$FRONTEND_BUILD_URI"
      ls -lh
      tar -xvzf build.tar.gz
      rm build.tar.gz
      cd -
    - ls -lh caen_tools/WebService/frontend
    - python3 -m pip install --upgrade build
    - python3 -m build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

badge_doc_cover:
  stage: build
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/python:3.11-alpine
  before_script:
    - echo "Install python dependencies"
    - pip install anybadge interrogate==1.7.0
  script:
    - ls
    - interrogate -m -n -p -vv caen_tools -f 0 -o docs_coverage.txt
    - cat docs_coverage.txt
    - covlevel=$(tail -n 1 docs_coverage.txt | cut -d " " -f7 | cut -d "%" -f1)
    - anybadge -l "Docs coverage" -v "$covlevel" --suffix='%' -f docs_coverage.svg 50=red 60=orange 80=yellow 100=green
  artifacts:
    paths:
      - docs_coverage.svg
      - docs_coverage.txt
    expire_in: never

upload_package:
  stage: release
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/python:3.11-alpine
  variables:
    TWINE_USERNAME: "gitlab-ci-token"
    TWINE_PASSWORD: "$CI_JOB_TOKEN"
  needs:
    - job: build_wheel
      artifacts: true
  script:
    - ls -lh
    - echo "$TWINE_USERNAME $TWINE_PASSWORD"
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
    - |
      PACKAGE_VERSION=$(python -c "from glob import glob; print(glob('dist/*.whl')[0].split('-')[1])")
      echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> package.env
  artifacts:
    reports:
      dotenv: package.env
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "release"
    - when: manual

deploy_development:
  stage: deploy
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/alpine:3.20
  needs: ['upload_package']
  when: manual
  variables:
    HOST: $SSH_DEV509_HOST
    PORT: $SSH_DEV509_PORT
    USER: $SSH_DEV509_USERNAME
    KEY: $SSH_DEV509_PRIVATE_KEY
    WORK_DIR: /caen
  before_script:
    - apk add openssh-client
    - mkdir -p ~/.ssh
    - echo "$KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -p $PORT $HOST >> ~/.ssh/known_hosts
    - printenv | grep -E "PACKAGE_VERSION" > local.env
  script:
    - ls -lh
    - scp -P $PORT $USER@$HOST:$WORK_DIR/.env remote.env
    - awk -F= '!seen[$1]++' local.env remote.env > .env
    - scp -P $PORT .env $USER@$HOST:$WORK_DIR/.
    - ssh -p $PORT "$USER@$HOST" "mkdir -p /caen/store; ls -lh /caen"
  environment: development
