name: Build Python package
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Build package
        shell: bash
        run: |
          ls -l
          cd caen_tools/WebService/frontend
          git submodule init
          git submodule update
          ls -l caen_tools/WebService/frontend
          npm install
          npm run build
          ls -l caen_tools/WebService/frontend

